version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:895047953283:task-definition/aws-hello-world-rest-api:3"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api-pipeline"
          ContainerPort: "80"
        PlatformVersion: "LATEST"